### PR TITLE
Updating the phishing URLs notebook example

### PR DESCRIPTION
**Pull request by shaypal5**
Just updating the phishing URLs notebook example I created a couple of weeks ago. The custom preprocessing object class now resides in `deepchecks/datasets/classification/phishing.py`, next to the code fetching the dataset. This makes the notebook's code less prone to break if moved around (relative to putting it in a script next to it, for example) and also cleaner.

I've also streamlined and shortened the last part of the notebooks, and as we go the RandomForestClassifier to the GradientBoostingClassifier we get a nice demonstration of the Boosting Overfit check.

I'm attaching here an updated version of the synthetic dataset I've generated for this scenario. Note that notebook results won't reproduce the currently committed dataset.

Cheers,
Shay

[phishing_urls_2019_rare.csv](https://github.com/deepchecks/deepchecks/files/7854703/phishing_urls_2019_rare.csv)

### CODE REVIEW

**Review by noamzbr — COMMENTED** [review]
Hi, note that currently the notebook returns an error:
`NameError: name 'UrlDatasetProcessor' is not defined`
So need to commit a fixed version

"Now with a random forest we get perfect precision" - Think you meant "gradient boosted trees" here.

**Comment by shaypal5** [comment]
The name `URL` does not appear in the notebook:
image

As does the term "we get perfect precision":
image

I think you're looking at an old version. @noamzbr

**Comment by shaypal5** [comment]
Ok, I can see here that the rendered notebook shows these old errors:
https://github.com/deepchecks/deepchecks/blob/urlnb/docs/source/examples/use-cases/phishing_urls.ipynb

I'm not sure if it's the GitHub renderer cache or something on my end, although the commit seems to be fine.

**Comment by shaypal5** [comment]
Ok, found it. Stupid Jupyter problems overwrote my last 10 minutes of changes. The Typio Form Recovery Chrome extension saved me some work once again. I've found the lost texts (indeed in the old RandomForest section) and restored everything, including the missing bugged line. Commit coming soon.

**Comment by shaypal5** [comment]
Rebased over `main` and fixed everything. New bug popped up in the process. I'm pretty sure it's not my doing, as I haven't changed any code:

https://github.com/deepchecks/deepchecks/issues/597

**Review by noamzbr — APPROVED** [review]

**Pull request merged**
