### PR TITLE
[MLC-242] added check decorators;

### PR DESCRIPTION
**Pull request by yromanyshyn**
We need to provide a less boilerplate way for our users to define a check and first what comes to mind - decorators. Example:

```python
from deepchecks import (
    single_dataset_check, 
    two_datasets_check, 
    train_test_datasets_check, 
    model_check, 
    CheckResult, 
    CheckSuite
)


@single_dataset_check
def custom_single_dataset_check(dataset, model=None) -> CheckResult:
    ....

@two_datasets_check
def custom_two_datasets_check(dataset, baseline_dataset, model=None) -> CheckResult:
    ....



suite = CheckSuite(
   'Custom Suite',
   custom_single_dataset_check,
   custom_two_datasets_check
)



```

### CODE REVIEW

**Comment by matanper** [comment]
I don't understand why this is needed

**Comment by yromanyshyn** [comment]
@matanper 

It could be useful for cases when the users want to define their own custom checks,
especially when those checks are simple and implementing whole class for it looks like something redundant

**Comment by matanper** [comment]
I'm against the simplification (not specifically this, but any), so leaving this to you @noamzbr @ItayGabbay

**Comment by yromanyshyn** [comment]
I am closing this PR whereas currently this functionality is not needed
MLC-242 will be reconsidered

**Pull request closed without merging**
