### PR TITLE
added model wrapper

### PR DESCRIPTION
**Pull request by JKL98ISR**

### CODE REVIEW

**Comment by JKL98ISR** [comment]
I am sincerely not sure what to think about it.
It works but should we do it?

**Comment by JKL98ISR** [comment]
@ItayGabbay Just thought about something. maybe just add caching in the feature importance calculation file? like a dict of model, dataset

**Comment by JKL98ISR** [comment]
> @ItayGabbay Just thought about something. maybe just add caching in the feature importance calculation file? like a dict of model, dataset

though it will remove the option of cached predictions though

**Comment by yromanyshyn** [comment]
> @ItayGabbay Just thought about something. maybe just add caching in the feature importance calculation file? like a dict of model, dataset

@JKL98ISR try to use `lru_cache` decorator from `functools` module or take a look at the [cachetools](https://github.com/tkem/cachetools) package

**Comment by ItayGabbay** [comment]
@JKL98ISR as @yromanyshyn mentioned, I agree that lru_cache may solve some problems here. Overall I think this is really important since the feature importance calculation is a heavy process. 
I don't mind skipping the predictions cache for now if that makes things more complicated.

**Review by noamzbr — COMMENTED** [review]
General question - why not have the WrapperModel implement predict and predict_proba and handle it internally?

Also feature importance can be saved in an internal feature_importance_ and then no need to modify the feature importance func

**Comment by matanper** [comment]
Another problem, in `TrustScoreComparison` we are predicting on a sample, which is dataframe. so you the model wrapper won't work there

**Comment by JKL98ISR** [comment]
switched to lru

**Pull request closed without merging**
